routes/web.php
<?php
Route::get('/', function () {
    return redirect('/home');
});

// Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
/*$this->get('oauth2google', 'Auth\Oauth2Controller@oauth2google')->name('oauth2google');
$this->get('googlecallback', 'Auth\Oauth2Controller@googlecallback')->name('googlecallback');
$this->get('oauth2facebook', 'Auth\Oauth2Controller@oauth2facebook')->name('oauth2facebook');
$this->get('facebookcallback', 'Auth\Oauth2Controller@facebookcallback')->name('facebookcallback');
$this->get('oauth2github', 'Auth\Oauth2Controller@oauth2github')->name('oauth2github');
$this->get('githubcallback', 'Auth\Oauth2Controller@githubcallback')->name('githubcallback');*/

// Registration Routes...
/*$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');*/

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.email');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');*/


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('tests', 'TestsController');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('topics', 'TopicsController');
    Route::post('topics_mass_destroy', ['uses' => 'TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('questions_options', 'QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::resource('results', 'ResultsController');
    Route::post('results_mass_destroy', ['uses' => 'ResultsController@massDestroy', 'as' => 'results.mass_destroy']);

    //question level
    Route::resource('questionLevel', 'QuestionLevelController');

    //question level details
    Route::resource('questionLevelDetail', 'QuestionLevelDetailController');

    //Manage Package category
    Route::resource('packageCategory', 'PackageCategoryController');
    Route::post('categories_mass_destroy', ['uses' => 'PackageCategoryController@massDestroy', 'as' => 'packageCategory.mass_destroy']);

    //Manage Package
    Route::resource('packages', 'PackageController');

    //Manage Coupon
    Route::resource('coupons', 'CouponController');

    //Manange Shop
    Route::resource('shops', 'CouponShopController');

    //Manage Puzzles
    Route::resource('stages', 'StageController');

    //Manage Level
    Route::resource('levels', 'LevelController');

    //patterns
    Route::resource('patterns', 'PatternController');

    //Puzzles
    Route::resource('puzzles', 'PuzzleController');
    Route::post('load-pattern-schema','PatternSchemaController@patternSchema')->name('pattern-schema');
    Route::post('stage-wise-level','ManageDropDownController@levelListDependOnStage')->name('stage-wise-level');

    //Spin
    Route::resource('spinTopics', 'SpinTopicController');
    Route::post('spin_topic_mass_destroy', ['uses' => 'SpinTopicController@massDestroy', 'as' => 'spin_topic.mass_destroy']);

    //spin question
    Route::resource('spinQuestions', 'SpinQuestionController');
    Route::post('spin_question_mass_destroy', ['uses' => 'SpinTopicController@massDestroy', 'as' => 'spinQuestions.mass_destroy']);

    //spin question Option
    Route::resource('spin_questions_options', 'SpinQuestionOptionController');
    Route::post('spin_question_option_mass_destroy', ['uses' => 'SpinQuestionOptionController@massDestroy', 'as' => 'spin_questions_options.mass_destroy']);

    //Manage User
    Route::resource('app-users','AppUsersController');
    Route::resource('user_levels','UserLevelController');
    Route::get('push-notification','PushNotificationController@push')->name('push');
    Route::post('send-push','PushNotificationController@sendPush')->name('push.send');

    //APK Update Manager
    Route::resource('apk-manage','ApkUpdateManagerController');

    //settings
    Route::resource('settings','SettingController');
    Route::resource('pointSettings','PointSettingController');


    //settings
    Route::match(array('GET', 'POST'), '/generate-leader-board','ReportsController@generateLeaderBoard')->name('reports.leader_board');

    //Route::get('generate-leader-board','ReportsController@generateLeaderBoard')->name('reports.leader_board');
    Route::post('leader-board-result','ReportsController@generateLeaderBoardResult')->name('reports.leader_board.result');

    /*===========================================Manage Live======================================
    //
    =============================================================================================*/
    //Manage Live
    Route::resource('lives','LiveController');
    Route::get('lives/results/{id}','LiveController@result')->name('lives.results');
    Route::get('lives/register/{id}','LiveController@interestedToJoinLive')->name('lives.register');

    //Question stage
    Route::resource('question_stages','QuestionStageController');

    //Live Question
    Route::resource('live_questions','LiveQuestionController');
    Route::post('live_question_schema','LiveQuestionController@questionSchema')->name('question-schema');
    Route::post('live_questions_mass_destroy', ['uses' => 'LiveQuestionController@massDestroy', 'as' => 'live_questions.mass_destroy']);





    /*===========================================Manage Live======================================
    //
    =============================================================================================*/


});

app/LiveQuestion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LiveQuestion extends Model
{
    protected $fillable = ['live_id', 'stage_id', 'question'];

    public function live()
    {
       return $this->belongsTo(Live::class, 'live_id');
    }
    public function stage()
    {
        return $this->belongsTo(QuestionStage::class, 'stage_id');
    }

    public function options()
    {
        return $this->hasMany(LiveQuestionOption::class, 'question_id');
    }

    public function correctOptions()
    {
        return $this->hasOne(LiveQuestionOption::class, 'question_id')->where('answer',1);
    }
}

app/Http/Controllers/LiveQuestionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LiveQuestionRequest;
use App\LiveQuestion;
use App\LiveQuestionOption;
use App\QuestionStage;
use App\Repositories\LiveRepo;
use Illuminate\Http\Request;

class LiveQuestionController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = LiveQuestion::with('live')->has('options', '>=', 2)->with('correctOptions','stage')->orderBy('id', 'desc')->get();
        return view('live_questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $relations = [
            'stages' => QuestionStage::get()->pluck('name', 'id')->prepend('Please select a stage', ''),
        ];
        $answer_options = [
        '' => 'Select Answer',
        'option1' => 'Option #1',
        'option2' => 'Option #2',
    ];

        return view('live_questions.create', compact('answer_options')+ $relations);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LiveQuestionRequest $request)
    {
        $live = (new LiveRepo())->CheckLive();
        if (empty($live)) {
            return redirect()->back()->withErrors('Please create a live first');
        }
        //check question limit
        $stage_id = $request->stage_id;
        $live_id = $live->id;
        $crossQuestionLimit = (new LiveRepo)->checkStageQuestionLimit($live_id, $stage_id);
        if ($crossQuestionLimit) {
            return redirect()->back()->withErrors('You are cross your limit in this stage!!');
        }

        $data = $request->all();
        $data['live_id'] = $live->id;
        $question = LiveQuestion::create($data);

        foreach ($request->input() as $key => $value) {
            if(strpos($key, 'option') !== false && $value != '') {
                $status = $request->input('answer') == $key ? 1 : 0;
                LiveQuestionOption::create([
                    'question_id' => $question->id,
                    'option'      => $value,
                    'answer'     => $status
                ]);
            }
        }

        return redirect()->route('live_questions.index')->with('message', 'Saved successfully!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\LiveQuestion  $liveQuestion
     * @return \Illuminate\Http\Response
     */
    public function show(LiveQuestion $liveQuestion)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\LiveQuestion  $liveQuestion
     * @return \Illuminate\Http\Response
     */
    public function edit(LiveQuestion $liveQuestion)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\LiveQuestion  $liveQuestion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, LiveQuestion $liveQuestion)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\LiveQuestion  $liveQuestion
     * @return \Illuminate\Http\Response
     */
    public function destroy(LiveQuestion $liveQuestion)
    {
        //
    }

    public function questionSchema(Request $request)
    {
        if ($request->ajax()) {
            $stage_id = $request->stage_id;
            $stage = QuestionStage::whereId($stage_id)->first();
            $no_of_options = $stage->question_options;
            $data = view('live_questions.question_schema',compact('no_of_options'))->render();
            return response()->json(['schema'=>$data]);
        }
    }


    /**
     * Delete all selected User at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if ($request->input('ids')) {
            $entries = LiveQuestion::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->options()->delete();
                $entry->delete();
            }
        }
    }
}

resources/views/live_questions/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.live.Live Questions')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['live_questions.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.create')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('stage_id', 'Question Stage*', ['class' => 'control-label']) !!}
                    {!! Form::select('stage_id', $stages, old('stage_id'), ['class' => 'form-control']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('stage_id'))
                        <p class="help-block">
                            {{ $errors->first('stage_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', 'Question text*', ['class' => 'control-label']) !!}
                    {!! Form::textarea('question', old('question'), ['class' => 'form-control ', 'placeholder' => '', 'rows'=>'2']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
            <div id="question_options"></div>
        </div>
    </div>
    {!! Form::submit(trans('quickadmin.save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}

    <div id="loader"
         style="display:none;margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgba(102, 102, 102, 0.66);; z-index: 30001; opacity: 0.8;">
        <p style="position: absolute; color: White; top: 50%; left: 45%;">
            <img src='{{asset('/quickadmin/images/loading.gif')}}'>
        </p>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            //stage level wise pattern schema load
            $("select[name='stage_id']").change(function () {
                $("#question_options").empty();
                $('#question_options').hide();
                $("#loader").show();
                var stage_id = $(this).val();
                var token = $("input[name='_token']").val();
                //alert(level);
                if (stage_id !== '') {
                    $.ajax({
                        url: "<?php echo route('question-schema') ?>",
                        method: 'POST',
                        data: {stage_id: stage_id, _token: token},
                        beforeSend: function () {
                            // Show image container
                            $("#loader").show();
                        },
                        success: function (data) {
                            $('#question_options').show();
                            $("#question_options").html(data.schema);
                            $("#loader").hide();
                        }
                    });
                }
            });
        });
    </script>
@endsection

resources/views/live_questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questions.title')</h3>
    
    {!! Form::model($question, ['method' => 'PUT', 'route' => ['questions.update', $question->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('topic_id', 'Topic*', ['class' => 'control-label']) !!}
                    {!! Form::select('topic_id', $topics, old('topic_id'), ['class' => 'form-control']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('topic_id'))
                        <p class="help-block">
                            {{ $errors->first('topic_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', 'Question text*', ['class' => 'control-label']) !!}
                    {!! Form::textarea('question', old('question'), ['class' => 'form-control ', 'placeholder' => '', 'rows'=>'2']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/live_questions/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.live.Live Questions')</h3>

    <p>
        <a href="{{ route('live_questions.create') }}" class="btn btn-success">@lang('quickadmin.add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.list')
        </div>

        <div class="panel-body">
            <table class="table table-bordered table-striped {{ count($questions) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        <th>Live Date</th>
                        <th>Stage</th>
                        <th>Question</th>
                        <th>Answer</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($questions) > 0)
                        @foreach ($questions as $question)
                            <tr data-entry-id="{{ $question->id }}">
                                <td></td>
                                <td>{{ $question->live->from or '' }}</td>
                                <td>{{ $question->stage->name or '' }}</td>
                                <td>{{ $question->question or '' }}</td>
                                <td>{!! $question->correctOptions->option !!}</td>
                                <td>
                                    <a href="{{ route('live_questions.show',[$question->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.view')</a>
                                    <a href="{{ route('live_questions.edit',[$question->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.edit')</a>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.are_you_sure")."');",
                                        'route' => ['live_questions.destroy', $question->id])) !!}
                                    {!! Form::submit(trans('quickadmin.delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7">@lang('quickadmin.no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript')
    <script>
        window.route_mass_crud_entries_destroy = '{{ route('live_questions.mass_destroy') }}';
    </script>
@endsection

resources/views/live_questions/question_schema.blade.php
@php
  $answer_options = [
      '' => 'Select Answer'
  ];
@endphp
<div class="row">
    @for ($i = 1; $i <= $no_of_options; $i++)
        @php
            $answer_options = array_merge($answer_options, ["option$i" => "Option #$i"]);
        @endphp
        <div class="col-xs-6 form-group">
            {!! Form::label("option".$i, 'Option #'.$i, ['class' => 'control-label']) !!}
            {!! Form::text('option'.$i, old('option'.$i), ['class' => 'form-control ', 'placeholder' => '']) !!}
        </div>
    @endfor
</div>

<div class="row">
    <div class="col-xs-12 form-group">
        {!! Form::label('answer', 'Answer', ['class' => 'control-label']) !!}
        {!! Form::select('answer', $answer_options, old('answer'), ['class' => 'form-control']) !!}
        <p class="help-block"></p>
        @if($errors->has('answer'))
            <p class="help-block">
                {{ $errors->first('answer') }}
            </p>
        @endif
    </div>
</div>

resources/views/live_questions/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questions.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Question</th>
                            <td>{{ $question->question or '' }}</td>
                        </tr>
                        @foreach($question->options as $key => $option)
                            <tr>
                                <th>Option-{{++$key}}</th>
                                <td>{{ $option->option or '' }}</td>
                            </tr>
                        @endforeach
                        <tr>
                            <th>Answer</th>
                            <td>{!! $question->correctOptions->option !!}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('questions.index') }}" class="btn btn-default">@lang('quickadmin.back_to_list')</a>
        </div>
    </div>
@stop