routes/web.php
<?php
Route::get('/', function () {
    return redirect('/home');
});

// Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
/*$this->get('oauth2google', 'Auth\Oauth2Controller@oauth2google')->name('oauth2google');
$this->get('googlecallback', 'Auth\Oauth2Controller@googlecallback')->name('googlecallback');
$this->get('oauth2facebook', 'Auth\Oauth2Controller@oauth2facebook')->name('oauth2facebook');
$this->get('facebookcallback', 'Auth\Oauth2Controller@facebookcallback')->name('facebookcallback');
$this->get('oauth2github', 'Auth\Oauth2Controller@oauth2github')->name('oauth2github');
$this->get('githubcallback', 'Auth\Oauth2Controller@githubcallback')->name('githubcallback');*/

// Registration Routes...
/*$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');*/

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.email');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');*/


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('tests', 'TestsController');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('topics', 'TopicsController');
    Route::post('topics_mass_destroy', ['uses' => 'TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('questions_options', 'QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::resource('results', 'ResultsController');
    Route::post('results_mass_destroy', ['uses' => 'ResultsController@massDestroy', 'as' => 'results.mass_destroy']);

    //question level
    Route::resource('questionLevel', 'QuestionLevelController');

    //question level details
    Route::resource('questionLevelDetail', 'QuestionLevelDetailController');

    //Manage Package category
    Route::resource('packageCategory', 'PackageCategoryController');
    Route::post('categories_mass_destroy', ['uses' => 'PackageCategoryController@massDestroy', 'as' => 'packageCategory.mass_destroy']);

    //Manage Package
    Route::resource('packages', 'PackageController');

    //Manage Coupon
    Route::resource('coupons', 'CouponController');

    //Manange Shop
    Route::resource('shops', 'CouponShopController');

    //Manage Puzzles
    Route::resource('stages', 'StageController');

    //Manage Level
    Route::resource('levels', 'LevelController');

    //patterns
    Route::resource('patterns', 'PatternController');

    //Puzzles
    Route::resource('puzzles', 'PuzzleController');
    Route::post('load-pattern-schema','PatternSchemaController@patternSchema')->name('pattern-schema');
    Route::post('stage-wise-level','ManageDropDownController@levelListDependOnStage')->name('stage-wise-level');

    //Spin
    Route::resource('spinTopics', 'SpinTopicController');
    Route::post('spin_topic_mass_destroy', ['uses' => 'SpinTopicController@massDestroy', 'as' => 'spin_topic.mass_destroy']);

    //spin question
    Route::resource('spinQuestions', 'SpinQuestionController');
    Route::post('spin_question_mass_destroy', ['uses' => 'SpinTopicController@massDestroy', 'as' => 'spinQuestions.mass_destroy']);

    //spin question Option
    Route::resource('spin_questions_options', 'SpinQuestionOptionController');
    Route::post('spin_question_option_mass_destroy', ['uses' => 'SpinQuestionOptionController@massDestroy', 'as' => 'spin_questions_options.mass_destroy']);

    //Manage User
    Route::resource('app-users','AppUsersController');
    Route::resource('user_levels','UserLevelController');
    Route::get('push-notification','PushNotificationController@push')->name('push');
    Route::post('send-push','PushNotificationController@sendPush')->name('push.send');

    //APK Update Manager
    Route::resource('apk-manage','ApkUpdateManagerController');

    //settings
    Route::resource('settings','SettingController');
    Route::resource('pointSettings','PointSettingController');


    //settings
    Route::match(array('GET', 'POST'), '/generate-leader-board','ReportsController@generateLeaderBoard')->name('reports.leader_board');

    //Route::get('generate-leader-board','ReportsController@generateLeaderBoard')->name('reports.leader_board');
    Route::post('leader-board-result','ReportsController@generateLeaderBoardResult')->name('reports.leader_board.result');

    /*===========================================Manage Live======================================
    //
    =============================================================================================*/
    //Manage Live
    Route::resource('lives','LiveController');
    Route::get('lives/results/{id}','LiveController@result')->name('lives.results');
    Route::get('lives/register/{id}','LiveController@interestedToJoinLive')->name('lives.register');

    //Question stage
    Route::resource('question_stages','QuestionStageController');

    //Live Question
    Route::resource('live_questions','LiveQuestionController');
    Route::post('live_question_schema','LiveQuestionController@questionSchema')->name('question-schema');
    Route::post('live_questions_mass_destroy', ['uses' => 'LiveQuestionController@massDestroy', 'as' => 'live_questions.mass_destroy']);





    /*===========================================Manage Live======================================
    //
    =============================================================================================*/


});

resources/views/apk_manager/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.apk.manage_apk')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['apk-manage.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('version', 'Version*', ['class' => 'control-label']) !!}
                    {!! Form::text('version', old('version'), ['class' => 'form-control', 'placeholder' => 'Enter Version Name']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('version'))
                        <p class="help-block">
                            {{ $errors->first('version') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('short_description', 'Release Note*', ['class' => 'control-label']) !!}
                    {!! Form::text('short_description', old('short_description'), ['class' => 'form-control', 'placeholder' => 'Enter Release Note']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('short_description'))
                        <p class="help-block">
                            {{ $errors->first('short_description') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('is_current_version', 'Is Current Version*', ['class' => 'control-label']) !!}
                    {!! Form::select('is_current_version', $conditionalValue, old('is_current_version'), ['class' => 'form-control']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('is_current_version'))
                        <p class="help-block">
                            {{ $errors->first('is_current_version') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('need_to_force', 'Need To Force Update*', ['class' => 'control-label']) !!}
                    {!! Form::select('need_to_force', $conditionalValue, old('need_to_force'), ['class' => 'form-control']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('need_to_force'))
                        <p class="help-block">
                            {{ $errors->first('need_to_force') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/apk_manager/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.apk.manage_apk')</h3>
    
    {!! Form::model($apk_manage, ['method' => 'PUT', 'route' => ['apk-manage.update', $apk_manage->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('version', 'Version*', ['class' => 'control-label']) !!}
                    {!! Form::text('version', old('version'), ['class' => 'form-control', 'placeholder' => 'Enter Version Name']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('version'))
                        <p class="help-block">
                            {{ $errors->first('version') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('short_description', 'Release Note*', ['class' => 'control-label']) !!}
                    {!! Form::text('short_description', old('short_description'), ['class' => 'form-control', 'placeholder' => 'Enter Release Note']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('short_description'))
                        <p class="help-block">
                            {{ $errors->first('short_description') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('is_current_version', 'Is Current Version*', ['class' => 'control-label']) !!}
                    {!! Form::select('is_current_version', $conditionalValue, old('is_current_version'), ['class' => 'form-control', "disabled"]) !!}
                    <p class="help-block"></p>
                    @if($errors->has('is_current_version'))
                        <p class="help-block">
                            {{ $errors->first('is_current_version') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('need_to_force', 'Need To Force Update*', ['class' => 'control-label']) !!}
                    {!! Form::select('need_to_force', $conditionalValue, old('need_to_force'), ['class' => 'form-control']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('need_to_force'))
                        <p class="help-block">
                            {{ $errors->first('need_to_force') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/apk_manager/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.apk.manage_apk')</h3>

    <p>
        <a href="{{ route('apk-manage.create') }}" class="btn btn-success">@lang('quickadmin.add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.list')
        </div>

        <div class="panel-body">
            <table class="table table-bordered table-striped {{ count($items) > 0 ? 'datatable' : '' }}">
                <thead>
                <tr>
                    <th style="text-align:center;">Sr</th>
                    <th>APK Version</th>
                    <th>Release Note</th>
                    <th>Current Version</th>
                    <th>Need To Force</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody>
                @if (count($items) > 0)
                    @foreach ($items as $key => $item)
                        <tr data-entry-id="{{ $item->id }}">
                            <td>{{++$key}}</td>
                            <td>{{ $item->version }}</td>
                            <td>{{ $item->short_description }}</td>
                            <td>
                                @if($item->is_current_version == 1)
                                    <label class="success">Yes</label>
                                @else
                                    <label class="danger">No</label>
                                @endif
                            </td>
                            <td>
                                @if($item->need_to_force == 1)
                                    <label class="success">Yes</label>
                                @else
                                    <label class="danger">No</label>
                                @endif
                            </td>

                            <td>
                                @if($item->is_current_version == 1)
                                    <a href="{{ route('apk-manage.edit',[$item->id]) }}"
                                       class="btn btn-xs btn-info">@lang('quickadmin.edit')</a>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="3">@lang('quickadmin.no_entries_in_table')</td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript')
    {{-- <script>
         window.route_mass_crud_entries_destroy = '{{ route('stages.mass_destroy') }}';
     </script>--}}
@endsection

resources/views/apk_manager/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.coupon.coupon')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Name</th>
                            <td>{{ $coupon->name }}</td>
                        </tr>
                        <tr>
                            <th>Need Point</th>
                            <td>{{ $coupon->need_point }}</td>
                        </tr>
                        <tr>
                            <th>Amount</th>
                            <td>{{ $coupon->amount }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('coupons.index') }}" class="btn btn-default">@lang('quickadmin.back_to_list')</a>
        </div>
    </div>
@stop